# Alacritty port of the Raider.vim theme by Alex Vear.
#
# Public domain.  No rights reserved.
#
# https://github.com/axvr/raider.vim/blob/master/ports/alacritty/raider-theme.toml

[window]
decorations_theme_variant = 'Dark'

[colors.primary]
background = '#222222'
foreground = '#c9c9c9'
dim_foreground = '#828282'

[colors.normal]
black = '#363636'
red = '#cf4c4c'
green = '#679d80'
yellow = '#a79180'
blue = '#94baca'
magenta = '#c061cb'
cyan = '#858ca6'
white = '#c9c9c9'

[colors.bright]
black = '#828282'
red = '#88766f'
green = '#2bb469'
yellow = '#ecb55d'
blue = '#3465a4'
magenta = '#75507b'
cyan = '#29acc1'
white = '#c9c9c9'

[colors.search]
matches = { foreground = '#222222', background = '#94baca' }
focused_match = { foreground = '#222222', background = '#ecb55d' }
